name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This runs the pipeline when code is pushed to the main branch
  pull_request:
    branches:
      - main  # This runs the pipeline when a pull request is made to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t my-fastapi-app .

      - name: Run Tests
        run: |
          pytest tests/  # Assuming you have tests in a 'tests' directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server (Example using SSH and Docker)
        run: |
          ssh user@your-server-ip 'docker pull my-fastapi-app && docker run -d -p 80:80 my-fastapi-app'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Add private key as GitHub secret
